/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  AssetInformationOnNetwork,
  AssetInformationOnNetworkInterface,
} from "../AssetInformationOnNetwork";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "assetInformation",
    outputs: [
      {
        internalType: "address",
        name: "assetAddress",
        type: "address",
      },
      {
        internalType: "bool",
        name: "bridgedToNetwork",
        type: "bool",
      },
      {
        internalType: "bool",
        name: "borrowedOnBridgedNetwork",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "bridgedQuantiy",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "address",
        name: "assetAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "bridgedQuantity",
        type: "uint256",
      },
    ],
    name: "bridgeAssetToNetwork",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "address",
        name: "assetAddress",
        type: "address",
      },
      {
        internalType: "bool",
        name: "borrowStatus",
        type: "bool",
      },
    ],
    name: "updateBorrowStatusOfAsset",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610394806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80632e70259a14610046578063443c6f0b14610094578063e9804c2b146100e4575b600080fd5b6100926004803603604081101561005c57600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff16906020019092919080359060200190929190505050610185565b005b6100e2600480360360408110156100aa57600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803515159060200190929190505050610298565b005b610126600480360360208110156100fa57600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff1690602001909291905050506102f5565b604051808573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001841515151581526020018315151515815260200182815260200194505050505060405180910390f35b60405180608001604052808373ffffffffffffffffffffffffffffffffffffffff168152602001600115158152602001600015158152602001828152506000808473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008201518160000160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555060208201518160000160146101000a81548160ff02191690831515021790555060408201518160000160156101000a81548160ff021916908315150217905550606082015181600101559050505050565b806000808473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060000160156101000a81548160ff0219169083151502179055505050565b60006020528060005260406000206000915090508060000160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff16908060000160149054906101000a900460ff16908060000160159054906101000a900460ff1690806001015490508456fea265627a7a72315820fc074747b61a6d0977f068acc715efafa8e76a3bca9682fb626bf4b4c4eda68e64736f6c634300050e0032";

export class AssetInformationOnNetwork__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<AssetInformationOnNetwork> {
    return super.deploy(overrides || {}) as Promise<AssetInformationOnNetwork>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): AssetInformationOnNetwork {
    return super.attach(address) as AssetInformationOnNetwork;
  }
  connect(signer: Signer): AssetInformationOnNetwork__factory {
    return super.connect(signer) as AssetInformationOnNetwork__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AssetInformationOnNetworkInterface {
    return new utils.Interface(_abi) as AssetInformationOnNetworkInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AssetInformationOnNetwork {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as AssetInformationOnNetwork;
  }
}
