/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "CmaSc",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CmaSc__factory>;
    getContractFactory(
      name: "Commons",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Commons__factory>;
    getContractFactory(
      name: "InsuranceSc",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InsuranceSc__factory>;
    getContractFactory(
      name: "Loans",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Loans__factory>;
    getContractFactory(
      name: "AssetInformationOnNetwork",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AssetInformationOnNetwork__factory>;
    getContractFactory(
      name: "Storage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Storage__factory>;
    getContractFactory(
      name: "Asset",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Asset__factory>;

    getContractAt(
      name: "CmaSc",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CmaSc>;
    getContractAt(
      name: "Commons",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Commons>;
    getContractAt(
      name: "InsuranceSc",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.InsuranceSc>;
    getContractAt(
      name: "Loans",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Loans>;
    getContractAt(
      name: "AssetInformationOnNetwork",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AssetInformationOnNetwork>;
    getContractAt(
      name: "Storage",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Storage>;
    getContractAt(
      name: "Asset",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Asset>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
