/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface InsuranceScInterface extends ethers.utils.Interface {
  functions: {
    "balances(address)": FunctionFragment;
    "farmerAddress()": FunctionFragment;
    "grainDetail()": FunctionFragment;
    "insuranceDetails()": FunctionFragment;
    "isAudit()": FunctionFragment;
    "isInsurance()": FunctionFragment;
    "numberOfCmaAudits()": FunctionFragment;
    "numberOfLoans()": FunctionFragment;
    "owner()": FunctionFragment;
    "updateInsurance(string,bytes32,uint256,uint256,uint256,bool)": FunctionFragment;
    "valuePerToken()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "balances", values: [string]): string;
  encodeFunctionData(
    functionFragment: "farmerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grainDetail",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "insuranceDetails",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isAudit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isInsurance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "numberOfCmaAudits",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "numberOfLoans",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateInsurance",
    values: [
      string,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "valuePerToken",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "farmerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grainDetail",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "insuranceDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isAudit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isInsurance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numberOfCmaAudits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numberOfLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateInsurance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "valuePerToken",
    data: BytesLike
  ): Result;

  events: {};
}

export class InsuranceSc extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: InsuranceScInterface;

  functions: {
    balances(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, number] & {
        freeTokens: BigNumber;
        lienTokens: BigNumber;
        walletType: number;
      }
    >;

    farmerAddress(overrides?: CallOverrides): Promise<[string]>;

    grainDetail(
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        boolean,
        BigNumber,
        number
      ] & {
        otherDetails: string;
        commodity: string;
        quantity: BigNumber;
        timestamp: BigNumber;
        expiryDate: BigNumber;
        repaymentLoanAmount: BigNumber;
        marketValueAtTheTimeDepositPerUnit: BigNumber;
        totalMarketValue: BigNumber;
        deliveredToken: BigNumber;
        lienToken: BigNumber;
        lienStatus: boolean;
        totalLoanAmount: BigNumber;
        whrStatus: number;
      }
    >;

    insuranceDetails(
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, BigNumber, BigNumber, boolean] & {
        componyName: string;
        policeId: string;
        amount: BigNumber;
        fromDate: BigNumber;
        endDate: BigNumber;
        status: boolean;
      }
    >;

    isAudit(overrides?: CallOverrides): Promise<[boolean]>;

    isInsurance(overrides?: CallOverrides): Promise<[boolean]>;

    numberOfCmaAudits(overrides?: CallOverrides): Promise<[number]>;

    numberOfLoans(overrides?: CallOverrides): Promise<[number]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    updateInsurance(
      _componyName: string,
      _policeId: BytesLike,
      _amount: BigNumberish,
      _fromDate: BigNumberish,
      _endDate: BigNumberish,
      _status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    valuePerToken(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  balances(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, number] & {
      freeTokens: BigNumber;
      lienTokens: BigNumber;
      walletType: number;
    }
  >;

  farmerAddress(overrides?: CallOverrides): Promise<string>;

  grainDetail(
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      boolean,
      BigNumber,
      number
    ] & {
      otherDetails: string;
      commodity: string;
      quantity: BigNumber;
      timestamp: BigNumber;
      expiryDate: BigNumber;
      repaymentLoanAmount: BigNumber;
      marketValueAtTheTimeDepositPerUnit: BigNumber;
      totalMarketValue: BigNumber;
      deliveredToken: BigNumber;
      lienToken: BigNumber;
      lienStatus: boolean;
      totalLoanAmount: BigNumber;
      whrStatus: number;
    }
  >;

  insuranceDetails(
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber, BigNumber, BigNumber, boolean] & {
      componyName: string;
      policeId: string;
      amount: BigNumber;
      fromDate: BigNumber;
      endDate: BigNumber;
      status: boolean;
    }
  >;

  isAudit(overrides?: CallOverrides): Promise<boolean>;

  isInsurance(overrides?: CallOverrides): Promise<boolean>;

  numberOfCmaAudits(overrides?: CallOverrides): Promise<number>;

  numberOfLoans(overrides?: CallOverrides): Promise<number>;

  owner(overrides?: CallOverrides): Promise<string>;

  updateInsurance(
    _componyName: string,
    _policeId: BytesLike,
    _amount: BigNumberish,
    _fromDate: BigNumberish,
    _endDate: BigNumberish,
    _status: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  valuePerToken(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    balances(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, number] & {
        freeTokens: BigNumber;
        lienTokens: BigNumber;
        walletType: number;
      }
    >;

    farmerAddress(overrides?: CallOverrides): Promise<string>;

    grainDetail(
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        boolean,
        BigNumber,
        number
      ] & {
        otherDetails: string;
        commodity: string;
        quantity: BigNumber;
        timestamp: BigNumber;
        expiryDate: BigNumber;
        repaymentLoanAmount: BigNumber;
        marketValueAtTheTimeDepositPerUnit: BigNumber;
        totalMarketValue: BigNumber;
        deliveredToken: BigNumber;
        lienToken: BigNumber;
        lienStatus: boolean;
        totalLoanAmount: BigNumber;
        whrStatus: number;
      }
    >;

    insuranceDetails(
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, BigNumber, BigNumber, boolean] & {
        componyName: string;
        policeId: string;
        amount: BigNumber;
        fromDate: BigNumber;
        endDate: BigNumber;
        status: boolean;
      }
    >;

    isAudit(overrides?: CallOverrides): Promise<boolean>;

    isInsurance(overrides?: CallOverrides): Promise<boolean>;

    numberOfCmaAudits(overrides?: CallOverrides): Promise<number>;

    numberOfLoans(overrides?: CallOverrides): Promise<number>;

    owner(overrides?: CallOverrides): Promise<string>;

    updateInsurance(
      _componyName: string,
      _policeId: BytesLike,
      _amount: BigNumberish,
      _fromDate: BigNumberish,
      _endDate: BigNumberish,
      _status: boolean,
      overrides?: CallOverrides
    ): Promise<boolean>;

    valuePerToken(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    balances(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    farmerAddress(overrides?: CallOverrides): Promise<BigNumber>;

    grainDetail(overrides?: CallOverrides): Promise<BigNumber>;

    insuranceDetails(overrides?: CallOverrides): Promise<BigNumber>;

    isAudit(overrides?: CallOverrides): Promise<BigNumber>;

    isInsurance(overrides?: CallOverrides): Promise<BigNumber>;

    numberOfCmaAudits(overrides?: CallOverrides): Promise<BigNumber>;

    numberOfLoans(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    updateInsurance(
      _componyName: string,
      _policeId: BytesLike,
      _amount: BigNumberish,
      _fromDate: BigNumberish,
      _endDate: BigNumberish,
      _status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    valuePerToken(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    balances(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    farmerAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    grainDetail(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    insuranceDetails(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isAudit(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isInsurance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    numberOfCmaAudits(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    numberOfLoans(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    updateInsurance(
      _componyName: string,
      _policeId: BytesLike,
      _amount: BigNumberish,
      _fromDate: BigNumberish,
      _endDate: BigNumberish,
      _status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    valuePerToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
