const Web3 = require('web3');
const ethNetwork = 'https://alfajores-forno.celo-testnet.org';
const web3 = new Web3(new Web3.providers.HttpProvider(ethNetwork));
const Routercontractjson = require('./artifacts/contracts/BruRouter.sol/BruRouter.json');
const poolContractjson = require('./artifacts/contracts/core/BruPool.sol/BruPool.json');
//const poolfactoryjson = require('../artifacts/contracts/BruFactory.json')
// const RoutercontractAddress = process.env.CONTRACT_ADDRESS;
process.env.WALLET_ADDRESS = '0x148e772046B59f5A61ea0F0322110eCE5f6bb146'
process.env.PRIVATE_KEY = '46ec2668343d0c648ff3f9c628075a4889f80fe7524fa08f8f64913d918bf760'
const RoutercontractAddress = "0xD2688226CD29a4047caB48B16Ea8ef08c1F52c95"
const routerContract = new web3.eth.Contract(
  Routercontractjson.abi,
  RoutercontractAddress
);
// const NFT = require('../models/nft');
//const factoryContract = new web3.eth.Contract(poolfactoryjson.abi,'0x48304A4ce97d7aB001bc176EEa953f18BC65eF18');
var noncecount = 0;
var totalMintedAmount = 0;
async function main() {
  try {
    let poolAddress = await routerContract.methods.getPoolAddress(0).call();

    console.log(poolAddress,"pool address");

    const poolContract = new web3.eth.Contract(
      poolContractjson.abi,
      poolAddress
    );
    console.log("reached here");
    // let nftresult = await poolContract.methods.nft("6272b4c9ad8c64b289b65172").call()
    // console.log(nftresult,"nft result")
    //let poolDetails = await factoryContract.methods.getPoolDetails().call();

    // console.log("pool details",poolDetails);
    // //   ///////--------------------- from here minting

    var data = {
      success: true,
      totalAssets: 4034,
      totalAssetsValue: 0,
      topCommodities: [],
      data: [
        {
          _id: '6272b4c8ad8c64b289b6516d',
          borrowedAmount: 0,
          borrowed: false,
          repaidAmount: 0,
          repaid: false,
          minted: true,
          mintedTransactionHash:
            '0x8de9755c5e5d122e2c5686acc5577d1fe400bb1a383e87bb38172fb87dc811ed',
          borrowTxHash: '',
          repayTxHash: '',
          network: '',
          pool: 1,
          commodity: 'Sorghum',
          commodityId: '5f02c0b869e6cd2702248ec1',
          quantity: 15000,
          interest: 0,
          platformCharges: 0,
          nftPrice: 450000,
          timestamp: '2022-05-04T17:15:52.704Z',
          ownerAddress: '0x148e772046B59f5A61ea0F0322110eCE5f6bb146',
          depositApplicationID: {
            address: {
              addressl2: null,
              village: 'Puna',
              district: 'Puna ',
              state: 'Maharashtra',
              pincode: '400062',
            },
            loanStatus: 'notApplied',
            hasSellOrder: false,
            whrSource: 'app',
            _id: '5ec1801b1347f32c6432f36c',
            timestamp: '2020-05-17T18:11:57.275Z',
            submittedBy: '5e22e6c75f9cce0e85e7a026',
            applicationType: 'mswcWhr',
            applicantName: 'Harshala',
            applicantEmail: 'harshalapawar266@gmail.com',
            applicantPhoneNo: '918108645202',
            warehouseName: 'Ann Dhan - Harshala Warehouse 1',
            wId: '5e60ac696e3c4791574c3585',
            acceptedByWarehouse: 'true',
            insuranceAdded: 'true',
            whReceiptId: 'WHR_30198_00006',
            aadhar: '21212',
            grainName: 'JAWAR',
            values: '450000.00 ',
            quantity: '15000.000 Kg',
            grade: 'C-FAIR',
            whrno: 'JD3',
            perUnitValue: '30',
            totalMarketValue: '450000.00 ',
            documentPath: 'nil',
            applicationStatus: 'approved',
            noOfBags: '500',
            salesOrder: '0000201630',
            strChanges: 6.7,
            advCharges: 0,
            mswcReceiptDate: 1589653147688,
            mswcReceiptExpDate: 1597515547688,
            mswcReceiptId: '17077712705',
            storageUnit: 'BAG',
            weightPerUnit: '30.000 ',
            marketRateUnit: '900.00 ',
            strCharges: 6.7,
            receiptBy: 'MSWCINFRASD',
            plant: '12',
            plantDesc: 'Gultekadi(A)Pune',
            stWhLoc: 'GULTEKADAOU02',
            stWhCode: 'OU02',
            lotNo: 'LOT06',
            category: 'NEGOTIABLE',
            custGroup: 'Traders',
            nomineeName: 'AMOD',
            materialcode: '1010000009',
            materialDesc: 'JAWAR',
            classGrade: 'C-FAIR',
            condition: 'C-FAIR',
            whrPackages: '500',
            idenMark: 'BAG RED',
            remark: 'GOOD 5',
            bagRange: '26-50 KG',
            uom: 'BAG',
            marketRate: '3000.00 ',
            mrateUom: 'QT',
            tax: 'NA',
            __v: 2,
            approvedTimestamp: '2020-05-17T18:19:10.427Z',
            bresponse: {
              code: 200,
              status: true,
              result: {
                contractAddress: '0xFb22FFb8F1366762Bd2e13084c57f91aa0650E7F',
                transactionHash:
                  '0x1b04d4a4c8257f3253257c3630faf656b1ea9c8dba3d5fc0e56bd08515927f53',
                status: true,
              },
              msg: 'success',
            },
            downloadCount: 34,
            labReport: [],
            qty: 15000,
            unit: 'KG',
            vehiclePhotos: [],
            weighBridgeSlip: [],
            blockchainReceiptId: 'WHR_30198_00006',
            qrCodesForBags: [],
            totalReceiptValue: 450000,
            depositQuantity: '15000.000 Kg',
            depositQty: 15000,
            depositUom: 'KG',
            commodityGrade: 'C-FAIR',
            commodityName: 'JAWAR',
            commodityId: {
              _id: '5f02c0b869e6cd2702248ec1',
              name: 'Jowar',
              maName: 'ज्वारी',
              hindiName: 'ज्वार',
              variants: [
                'JAWAR',
                'SORGUM / JAWAR',
                'JOWAR / SORGHUM',
                'JOWAR',
                'JOWAR / JAWAR / SORGHUM',
                'JOWAR-WHITE',
                'JOWAR-YELLOW',
                'JOWAR RED',
                'JOWAR-MIXED',
              ],
              __v: 6,
              units: ['KG', 'QT'],
              universalName: 'Sorghum',
            },
            aadharNo: '21212',
            warehouseNumber: 'JD3',
            mswcDepositDate: '2020-05-16',
            waddress: {
              waddressL1: 'Pune',
              waddressL2: 'Pune',
              wvillage: 'Pune',
              wdistrict: 'Pune',
              wregion: 'Pune',
              wstate: 'Maharashtra',
              wpincode: '42000',
            },
          },
          userId: null,
          dataHash: 'S5Ziv4Iq1gtgIqNge6tyf4piCtjj8a+N1VQ+XEWmcDU=',
          __v: 0,
        },
        {
          _id: '6272b4c8ad8c64b289b6516e',
          borrowedAmount: 20000000000000000000,
          borrowed: true,
          repaidAmount: 0,
          repaid: false,
          minted: true,
          mintedTransactionHash:
            '0x8614a6cdd2016801e10fe2d6b83529103a14e9c5ad6799ef25be204dd8107963',
          borrowTxHash: '',
          repayTxHash: '',
          network: '',
          pool: 1,
          commodity: 'Gram',
          commodityId: '5f5f0f5edeed643fcc3428a8',
          quantity: 7000,
          interest: 0,
          platformCharges: 0,
          nftPrice: 259000,
          timestamp: '2022-05-04T17:15:52.797Z',
          ownerAddress: '0x148e772046B59f5A61ea0F0322110eCE5f6bb146',
          depositApplicationID: {
            address: {
              addressl2: null,
              village: 'Yevati',
              district: 'Washim',
              state: 'Maharashtra',
              pincode: '444510',
            },
            hasSellOrder: false,
            whrSource: 'app',
            _id: '5ec26ce3fbf0cc2e51fdfa64',
            timestamp: '2020-05-17T19:10:26.696Z',
            submittedBy: '5ec26ce2fbf0cc2e51fdfa63',
            applicationType: 'mswcWhr',
            applicantName: 'SHANKAR KISAN SHINDE',
            applicantEmail: 'washim.wh@mswc.in',
            applicantPhoneNo: '9922280811',
            warehouseName: 'Ann Dhan - MSWC Washim',
            wId: '5ebd1d47bfba667737189840',
            acceptedByWarehouse: 'true',
            insuranceAdded: 'true',
            whReceiptId: 'WHR_15559_00008',
            aadhar: '244842405613',
            grainName: 'GRAM/CHANA',
            values: '259000.00 ',
            quantity: '7000.000 Kg',
            grade: 'B-AVERAGE',
            whrno: 'FL1',
            perUnitValue: '37',
            totalMarketValue: '259000.00 ',
            documentPath: 'nil',
            applicationStatus: 'approved',
            noOfBags: '70',
            salesOrder: '0000298658',
            strChanges: 10.85,
            advCharges: 0,
            mswcReceiptDate: 1589800163825,
            mswcReceiptExpDate: 1597662563825,
            mswcReceiptId: '1621106458',
            storageUnit: 'BAG',
            weightPerUnit: '100.000 ',
            marketRateUnit: '3700.00 ',
            strCharges: 10.85,
            receiptBy: 'WHR162101',
            plant: '1621',
            plantDesc: 'Washim',
            stWhLoc: 'WASHIMOU01',
            stWhCode: 'OU01',
            lotNo: 'LOTA3',
            category: 'NEGOTIABLE',
            custGroup: 'Farmers',
            nomineeName: 'SELF',
            materialcode: '1010000016',
            materialDesc: 'GRAM/CHANA',
            classGrade: 'B-AVERAGE',
            condition: 'B-AVERAGE',
            whrPackages: '70',
            idenMark: 'S.K.S.',
            remark: 'GOOD',
            bagRange: '51-100 KG',
            uom: 'BAG',
            marketRate: '3700.00 ',
            mrateUom: 'QT',
            tax: 'NA',
            __v: 2,
            approvedTimestamp: '2020-05-18T11:09:26.313Z',
            bresponse: {
              code: 200,
              status: true,
              result: {
                contractAddress: '0xE75CE3564C126eb5763dD4eb4435Fd2934Ea28FB',
                transactionHash:
                  '0x7f4f67d13e5c9831d5de02a578f5897dd0294bec4222f4b73581938fbb4ba260',
                status: true,
              },
              msg: 'success',
            },
            downloadCount: 27,
            loanStatus: 'applied',
            lienStatus: false,
            labReport: [],
            qty: 7000,
            unit: 'KG',
            vehiclePhotos: [],
            weighBridgeSlip: [],
            blockchainReceiptId: 'WHR_15559_00008',
            qrCodesForBags: [],
            totalReceiptValue: 259000,
            depositQuantity: '7000.000 Kg',
            depositQty: 7000,
            depositUom: 'KG',
            commodityGrade: 'B-AVERAGE',
            commodityName: 'GRAM/CHANA',
            commodityId: {
              _id: '5f5f0f5edeed643fcc3428a8',
              variants: [
                'GRAM/CHANA',
                'HORSE GRAM',
                'BENGAL GRAM/GRAM',
                'CHANA WHOLE',
                'CHANA',
                'CHANA WHOLE/BENGAL GRAM/GRAM',
                'BENGAL GRAM',
                'CHANA',
                'BENGALGRAM',
              ],
              name: 'Gram',
              maName: 'चने/हरभरा',
              hindiName: 'चने',
              __v: 3,
              units: ['KG', 'QT'],
              universalName: 'Gram',
            },
            aadharNo: '244842405613',
            warehouseNumber: 'FL1',
            mswcDepositDate: '2020-05-18',
            waddress: {
              waddressL1:
                'MSWC, Krushi Utpanna Bazar Samiti, Near Railway Station, Washim,',
              waddressL2: 'Washim',
              wvillage: 'Washim',
              wdistrict: 'Washim',
              wregion: 'Amravati',
              wstate: 'Maharashtra',
              wpincode: '444505',
            },
          },
          userId: null,
          dataHash: '9Sq2jvD12n8uAr34EVf02ZPhsVQdpouJAFP4Jm7kRnk=',
          __v: 0,
        },
        {
          _id: '6272b4c8ad8c64b289b6516f',
          borrowedAmount: 40000000000000000000,
          borrowed: true,
          repaidAmount: 0,
          repaid: false,
          minted: true,
          mintedTransactionHash:
            '0x21fa0a9e705ccf8874522d41250bf31811dd425af3fb55aff7db40c054e4cd52',
          borrowTxHash: '',
          repayTxHash: '',
          network: '',
          pool: 1,
          commodity: 'Turmeric',
          commodityId: '5f5f0f5edeed643fcc3428a6',
          quantity: 6106,
          interest: 0,
          platformCharges: 0,
          nftPrice: 457950,
          timestamp: '2022-05-04T17:15:52.873Z',
          ownerAddress: '0x148e772046B59f5A61ea0F0322110eCE5f6bb146',
          depositApplicationID: {
            address: {
              addressl2: null,
              village: 'Ozarde',
              district: 'Satara',
              state: 'Maharashtra',
              pincode: '412803',
            },
            hasSellOrder: false,
            whrSource: 'app',
            _id: '5ec2766b2b816235e1d044e5',
            timestamp: '2020-05-18T11:38:40.950Z',
            submittedBy: '5ec2766a2b816235e1d044e4',
            applicationType: 'mswcWhr',
            applicantName: 'SHELAR SAHEBRAO SHIVRAM',
            applicantEmail: 'phaltan.wh@mswc.in',
            applicantPhoneNo: '9822403440',
            warehouseName: 'Ann Dhan - MSWC Phaltan',
            wId: '5ebf3f9e1da7731058e710ce',
            acceptedByWarehouse: 'true',
            insuranceAdded: 'true',
            whReceiptId: 'WHR_93054_00009',
            aadhar: '948821518575',
            grainName: 'TARMARIC / HALDI',
            values: '457950.00 ',
            quantity: '6106.000 Kg',
            grade: 'B-AVERAGE',
            whrno: 'JH7',
            perUnitValue: '75',
            totalMarketValue: '457950.00 ',
            documentPath: 'nil',
            applicationStatus: 'approved',
            noOfBags: '71',
            salesOrder: '0000298687',
            strChanges: 10.7,
            advCharges: 0.6,
            mswcReceiptDate: 1589802603884,
            mswcReceiptExpDate: 1597665003884,
            mswcReceiptId: '1715103125',
            storageUnit: 'BAG',
            weightPerUnit: '86.000 ',
            marketRateUnit: '6450.00 ',
            strCharges: 10.7,
            receiptBy: 'WHR171501',
            plant: '1715',
            plantDesc: 'Phaltan',
            stWhLoc: 'PHALTANOU04',
            stWhCode: 'OU04',
            lotNo: 'LOT09',
            category: 'NEGOTIABLE',
            custGroup: 'Farmers',
            nomineeName: 'MAHESH SHELAR',
            materialcode: '1010000070',
            materialDesc: 'TARMARIC / HALDI',
            classGrade: 'B-AVERAGE',
            condition: 'B-AVERAGE',
            whrPackages: '71',
            idenMark: 'ZUTE BAGS',
            remark: 'OK',
            bagRange: '51-100 KG',
            uom: 'BAG',
            marketRate: '7500.00 ',
            mrateUom: 'QT',
            tax: 'NA',
            __v: 2,
            approvedTimestamp: '2020-05-18T11:50:05.222Z',
            bresponse: {
              code: 200,
              status: true,
              result: {
                contractAddress: '0x1c735014F66FECbf21BDCea2d23371bE3e977Aaf',
                transactionHash:
                  '0x50acd7030dc79ada5c33d4d94a4803f06fc839eddf49459fac7853a6f05b28f5',
                status: true,
              },
              msg: 'success',
            },
            downloadCount: 15,
            loanStatus: 'applied',
            lienStatus: false,
            labReport: [],
            qty: 6106,
            unit: 'KG',
            vehiclePhotos: [],
            weighBridgeSlip: [],
            blockchainReceiptId: 'WHR_93054_00009',
            qrCodesForBags: [],
            totalReceiptValue: 457950,
            depositQuantity: '6106.000 Kg',
            depositQty: 6106,
            depositUom: 'KG',
            commodityGrade: 'B-AVERAGE',
            commodityName: 'TARMARIC / HALDI',
            commodityId: {
              _id: '5f5f0f5edeed643fcc3428a6',
              variants: [
                'TURMERIC',
                'TARMARIC/HALDI',
                'HALDI',
                'TARMARIC',
                'TURMERIC BULB OLD',
                'TURMERIC PANANGALI',
                'TURMERIC FINGURE OLD',
                'TURMERIC ATTU',
                'TURMERIC CHURA',
                'TURMERIC BULB PRATHIBA',
                'TURMERIC BULB',
                'TURMERIC FINGER PRATHIBA',
                'TURMERIC FINGER',
                'Turmeric (Farmer Polished)',
                'Turmeric (Unpolished)',
              ],
              name: 'Turmeric',
              maName: 'हळद',
              hindiName: 'हल्दी',
              __v: 6,
              units: ['KG', 'QT'],
              universalName: 'Turmeric',
            },
            aadharNo: '948821518575',
            warehouseNumber: 'JH7',
            mswcDepositDate: '2020-05-18',
            waddress: {
              waddressL1: 'MSWC, Tambmal - Lonand Road, Phaltan,',
              waddressL2: 'Phaltan',
              wvillage: 'Phaltan',
              wdistrict: 'Satara',
              wregion: 'Kolhapur',
              wstate: 'Maharashtra',
              wpincode: '415523',
            },
          },
          userId: null,
          dataHash: '8dZNIUt2QrFf62LlDFi9azSzdlJGBJabvFNk/WyXmJo=',
          __v: 0,
        },
        {
          _id: '6272b4c8ad8c64b289b65170',
          borrowedAmount: 0,
          borrowed: false,
          repaidAmount: 0,
          repaid: false,
          minted: true,
          mintedTransactionHash:
            '0x8989f17e121f6d0d6d8e780d2688a1de9a047523eff3dd262da5e682705c9aa9',
          borrowTxHash: '',
          repayTxHash: '',
          network: '',
          pool: 1,
          commodity: 'Turmeric',
          commodityId: '5f5f0f5edeed643fcc3428a6',
          quantity: 6020,
          interest: 0,
          platformCharges: 0,
          nftPrice: 451500,
          timestamp: '2022-05-04T17:15:52.945Z',
          ownerAddress: '0x148e772046B59f5A61ea0F0322110eCE5f6bb146',
          depositApplicationID: {
            address: {
              addressl2: null,
              village: 'Ozarde',
              district: 'Satara',
              state: 'Maharashtra',
              pincode: '412803',
            },
            hasSellOrder: false,
            whrSource: 'app',
            _id: '5ec27a362b816235e1d044e8',
            timestamp: '2020-05-18T11:38:40.950Z',
            submittedBy: '5ec2766a2b816235e1d044e4',
            applicationType: 'mswcWhr',
            applicantName: 'SHELAR SAHEBRAO SHIVRAM',
            applicantEmail: 'phaltan.wh@mswc.in',
            applicantPhoneNo: '9822403440',
            warehouseName: 'Ann Dhan - MSWC Phaltan',
            wId: '5ebf3f9e1da7731058e710ce',
            acceptedByWarehouse: 'true',
            insuranceAdded: 'true',
            whReceiptId: 'WHR_22475_00010',
            aadhar: '948821518575',
            grainName: 'TARMARIC / HALDI',
            values: '451500.00 ',
            quantity: '6020.000 Kg',
            grade: 'B-AVERAGE',
            whrno: 'JH7',
            perUnitValue: '75',
            totalMarketValue: '451500.00 ',
            documentPath: 'nil',
            applicationStatus: 'approved',
            noOfBags: '70',
            salesOrder: '0000298707',
            strChanges: 10.7,
            advCharges: 0.6,
            mswcReceiptDate: 1589803574998,
            mswcReceiptExpDate: 1597665974998,
            mswcReceiptId: '1715103126',
            storageUnit: 'BAG',
            weightPerUnit: '86.000 ',
            marketRateUnit: '6450.00 ',
            strCharges: 10.7,
            receiptBy: 'WHR171501',
            plant: '1715',
            plantDesc: 'Phaltan',
            stWhLoc: 'PHALTANOU04',
            stWhCode: 'OU04',
            lotNo: 'LOT09',
            category: 'NEGOTIABLE',
            custGroup: 'Farmers',
            nomineeName: 'MAHESH SHELAR',
            materialcode: '1010000070',
            materialDesc: 'TARMARIC / HALDI',
            classGrade: 'B-AVERAGE',
            condition: 'B-AVERAGE',
            whrPackages: '70',
            idenMark: 'ZUTE BAGS',
            remark: 'OK',
            bagRange: '51-100 KG',
            uom: 'BAG',
            marketRate: '7500.00 ',
            mrateUom: 'QT',
            tax: 'NA',
            __v: 2,
            approvedTimestamp: '2020-05-18T12:06:17.446Z',
            bresponse: {
              code: 200,
              status: true,
              result: {
                contractAddress: '0x1c8212EB627FFA6B2a6B513145579fC47D2ccaa8',
                transactionHash:
                  '0xbd16b1ff6c340964ec380a746d53eb95842e533bea4e0214409c5eef6ac0b0ac',
                status: true,
              },
              msg: 'success',
            },
            downloadCount: 19,
            loanStatus: 'applied',
            lienStatus: false,
            labReport: [],
            qty: 6020,
            unit: 'KG',
            vehiclePhotos: [],
            weighBridgeSlip: [],
            blockchainReceiptId: 'WHR_22475_00010',
            qrCodesForBags: [],
            totalReceiptValue: 451500,
            depositQuantity: '6020.000 Kg',
            depositQty: 6020,
            depositUom: 'KG',
            commodityGrade: 'B-AVERAGE',
            commodityName: 'TARMARIC / HALDI',
            commodityId: {
              _id: '5f5f0f5edeed643fcc3428a6',
              variants: [
                'TURMERIC',
                'TARMARIC/HALDI',
                'HALDI',
                'TARMARIC',
                'TURMERIC BULB OLD',
                'TURMERIC PANANGALI',
                'TURMERIC FINGURE OLD',
                'TURMERIC ATTU',
                'TURMERIC CHURA',
                'TURMERIC BULB PRATHIBA',
                'TURMERIC BULB',
                'TURMERIC FINGER PRATHIBA',
                'TURMERIC FINGER',
                'Turmeric (Farmer Polished)',
                'Turmeric (Unpolished)',
              ],
              name: 'Turmeric',
              maName: 'हळद',
              hindiName: 'हल्दी',
              __v: 6,
              units: ['KG', 'QT'],
              universalName: 'Turmeric',
            },
            aadharNo: '948821518575',
            warehouseNumber: 'JH7',
            mswcDepositDate: '2020-05-18',
            waddress: {
              waddressL1: 'MSWC, Tambmal - Lonand Road, Phaltan,',
              waddressL2: 'Phaltan',
              wvillage: 'Phaltan',
              wdistrict: 'Satara',
              wregion: 'Kolhapur',
              wstate: 'Maharashtra',
              wpincode: '415523',
            },
          },
          userId: null,
          dataHash: '4++L6kU9bjxTD/c9JhcrWZRXUh5Z3nb4I2aV3IF6UPU=',
          __v: 0,
        },
        {
          _id: '6272b4c9ad8c64b289b65171',
          borrowedAmount: 0,
          borrowed: false,
          repaidAmount: 0,
          repaid: false,
          minted: true,
          mintedTransactionHash:
            '0xcd625657a870eea0f44d17a1caddb6cf1ad8b0df3e84dd1b253186d035005647',
          borrowTxHash: '',
          repayTxHash: '',
          network: '',
          pool: 1,
          commodity: 'Turmeric',
          commodityId: '5f5f0f5edeed643fcc3428a6',
          quantity: 12988,
          interest: 0,
          platformCharges: 0,
          nftPrice: 909160,
          timestamp: '2022-05-04T17:15:53.031Z',
          ownerAddress: '0x148e772046B59f5A61ea0F0322110eCE5f6bb146',
          depositApplicationID: {
            address: {
              addressl2: null,
              village: 'JEJURI',
              district: 'Pune',
              state: 'Maharashtra',
              pincode: '412303',
            },
            loanStatus: 'notApplied',
            hasSellOrder: false,
            whrSource: 'app',
            _id: '5ec27d226e9fab387a2a1c0a',
            timestamp: '2020-05-18T12:16:58.978Z',
            submittedBy: '5ec27d1e6e9fab387a2a1c09',
            applicationType: 'mswcWhr',
            applicantName: 'CHARMS CHEM PVT LTD JEJURI',
            applicantEmail: '',
            applicantPhoneNo: '7350970617',
            warehouseName: 'Ann Dhan - MSWC Phaltan',
            wId: '5ebf3f9e1da7731058e710ce',
            acceptedByWarehouse: 'true',
            insuranceAdded: 'true',
            whReceiptId: 'WHR_49956_00011',
            aadhar: '',
            grainName: 'TARMARIC / HALDI',
            values: '909160.00 ',
            quantity: '12988.000 Kg',
            grade: 'B-AVERAGE',
            whrno: 'JH7',
            perUnitValue: '70',
            totalMarketValue: '909160.00 ',
            documentPath: 'nil',
            applicationStatus: 'approved',
            noOfBags: '191',
            salesOrder: '0000298721',
            strChanges: 10.4,
            advCharges: 0.6,
            mswcReceiptDate: 1589804322874,
            mswcReceiptExpDate: 1597666722874,
            mswcReceiptId: '1715103127',
            storageUnit: 'BAG',
            weightPerUnit: '68.000 ',
            marketRateUnit: '4760.00 ',
            strCharges: 10.4,
            receiptBy: 'WHR171501',
            plant: '1715',
            plantDesc: 'Phaltan',
            stWhLoc: 'PHALTANOU04',
            stWhCode: 'OU04',
            lotNo: 'LOT10',
            category: 'NEGOTIABLE',
            custGroup: 'Traders',
            nomineeName: 'MANGESH JADHAV',
            materialcode: '1010000070',
            materialDesc: 'TARMARIC / HALDI',
            classGrade: 'B-AVERAGE',
            condition: 'B-AVERAGE',
            whrPackages: '191',
            idenMark: 'ZUTE BAGS',
            remark: 'OK',
            bagRange: '51-100 KG',
            uom: 'BAG',
            marketRate: '7000.00 ',
            mrateUom: 'QT',
            tax: 'NA',
            __v: 2,
            approvedTimestamp: '2020-05-18T12:18:44.222Z',
            bresponse: {
              code: 200,
              status: true,
              result: {
                contractAddress: '0x0Ca4AB50C1fbDDB1470b04225A9739fc8B3428c4',
                transactionHash:
                  '0xd4cffc7431e3582f5d6fb21ce9f185b1c400a3234bf492a3bef035093c57a2ac',
                status: true,
              },
              msg: 'success',
            },
            downloadCount: 0,
            labReport: [],
            qty: 12988,
            unit: 'KG',
            vehiclePhotos: [],
            weighBridgeSlip: [],
            blockchainReceiptId: 'WHR_49956_00011',
            qrCodesForBags: [],
            totalReceiptValue: 909160,
            depositQuantity: '12988.000 Kg',
            depositQty: 12988,
            depositUom: 'KG',
            commodityGrade: 'B-AVERAGE',
            commodityName: 'TARMARIC / HALDI',
            commodityId: {
              _id: '5f5f0f5edeed643fcc3428a6',
              variants: [
                'TURMERIC',
                'TARMARIC/HALDI',
                'HALDI',
                'TARMARIC',
                'TURMERIC BULB OLD',
                'TURMERIC PANANGALI',
                'TURMERIC FINGURE OLD',
                'TURMERIC ATTU',
                'TURMERIC CHURA',
                'TURMERIC BULB PRATHIBA',
                'TURMERIC BULB',
                'TURMERIC FINGER PRATHIBA',
                'TURMERIC FINGER',
                'Turmeric (Farmer Polished)',
                'Turmeric (Unpolished)',
              ],
              name: 'Turmeric',
              maName: 'हळद',
              hindiName: 'हल्दी',
              __v: 6,
              units: ['KG', 'QT'],
              universalName: 'Turmeric',
            },
            aadharNo: '',
            warehouseNumber: 'JH7',
            mswcDepositDate: '2020-05-18',
            waddress: {
              waddressL1: 'MSWC, Tambmal - Lonand Road, Phaltan,',
              waddressL2: 'Phaltan',
              wvillage: 'Phaltan',
              wdistrict: 'Satara',
              wregion: 'Kolhapur',
              wstate: 'Maharashtra',
              wpincode: '415523',
            },
          },
          userId: null,
          dataHash: 'D6F2l0xSu2fuswi9rFPfY6Mc+kzssP+EqPEvGqcWwbM=',
          __v: 0,
        },
        {
          _id: '6272b4c9ad8c64b289b65172',
          borrowedAmount: 30000000000000000000,
          borrowed: true,
          repaidAmount: 0,
          repaid: false,
          minted: true,
          mintedTransactionHash:
            '0xddf68fd4e8151cdaf72e9a0c1850323006a9f9e2704f1f752c1853ee5515967d',
          borrowTxHash: '',
          repayTxHash: '',
          network: '',
          pool: 1,
          commodity: 'Wheat',
          commodityId: '5f02c0b869e6cd2702248ecf',
          quantity: 15000,
          interest: 0,
          platformCharges: 0,
          nftPrice: 1500000,
          timestamp: '2022-05-04T17:15:53.091Z',
          ownerAddress: '0x148e772046B59f5A61ea0F0322110eCE5f6bb146',
          depositApplicationID: {
            address: {
              addressl2: null,
              village: 'Puna',
              district: 'Puna ',
              state: 'Maharashtra',
              pincode: '400062',
            },
            hasSellOrder: false,
            whrSource: 'app',
            _id: '5ec36db4be489e392867f8f3',
            timestamp: '2020-05-18T13:00:35.529Z',
            submittedBy: '5e22e6c75f9cce0e85e7a026',
            applicationType: 'lookingtodeposit',
            applicantName: 'Abhishek Bhattacharya',
            applicantEmail: 'abhib.work@gmail.com',
            applicantPhoneNo: '918527903420',
            warehouseName: 'Whrrl Warehouse',
            wId: '5ec366acbe489e392867f8f2',
            acceptedByWarehouse: 'true',
            insuranceAdded: 'false',
            whReceiptId: 'WHR_05755_00012',
            aadhar: '939339993933',
            grainName: 'WHEAT',
            values: '1500000',
            quantity: '15000 Kg',
            grade: 'A+',
            whrno: 'nil',
            perUnitValue: '100',
            totalMarketValue: '1500000',
            documentPath: 'nil',
            applicationStatus: 'approved',
            noOfBags: '1000',
            __v: 2,
            acceptedTimestamp: '2020-05-19T05:26:00.337Z',
            approvedTimestamp: '2020-05-19T05:47:03.618Z',
            bresponse: {
              code: 200,
              status: true,
              result: {
                contractAddress: '0x091e89D41EbbA246F59408dc87885e60aa1EA68D',
                transactionHash:
                  '0xc872f7ac619bf5510b10ed1b80ed88c3269d9061ce52a49f8f79559f790ffdfd',
                status: true,
              },
              msg: 'success',
            },
            downloadCount: 5,
            loanStatus: 'applied',
            lienStatus: true,
            labReport: [],
            qty: 15000,
            unit: 'KG',
            vehiclePhotos: [],
            weighBridgeSlip: [],
            blockchainReceiptId: 'WHR_05755_00012',
            qrCodesForBags: [],
            totalReceiptValue: 1500000,
            depositQuantity: '15000 Kg',
            depositQty: 15000,
            depositUom: 'KG',
            commodityGrade: 'A+',
            commodityName: 'WHEAT',
            commodityId: {
              _id: '5f02c0b869e6cd2702248ecf',
              name: 'Wheat',
              maName: 'गहू',
              hindiName: 'गहू',
              variants: [
                'WHEAT',
                'WHEAT(UNHUSKED)',
                'WHEAT(HUSKED)',
                'WHEAT-BHANSI',
                'WHEAT-HYBRID',
                'WHEAT-SARABHATI',
                'WHITE-GINGELY',
                'WHITE PEAS',
              ],
              __v: 6,
              units: ['KG', 'QT'],
              universalName: 'Wheat',
            },
            aadharNo: '939339993933',
            warehouseNumber: 'nil',
            waddress: {
              waddressL1: 'Thane West',
              waddressL2: 'Thane',
              wvillage: 'Mumbai',
              wdistrict: 'Mumbai',
              wregion: 'New Mumbai',
              wstate: 'Maharashtra',
              wpincode: '400604',
            },
          },
          userId: null,
          dataHash: '98njkzMssbtg6QQXY0ByX0P2FHQ0tx9J1L5O01SdrxA=',
          __v: 0,
        },
      ],
      totalAssetsValueMinted: 1239553904,
    };

       for (var i = 1; i < data.data.length; i++) {
         console.log(data.data[i]._id);
         console.log("---------------",i)
        var nftObject = {
          nftId: data.data[i]._id,
          commodity: data.data[i].commodity,
          commodityId: data.data[i].commodityId,
          quantity: data.data[i].quantity,
          nftPrice: data.data[i].nftPrice,
          pool: data.data[i].pool,
          dataHash: data.data[i].dataHash,
        };
        console.log("----------nftobject",nftObject);
        //  if (totalMintedAmount <= 1239008000) {
          if (
           data.data[i].nftPrice % 1 == 0 &&
           data.data[i].quantity % 1 == 0 &&
           //data.data[i].ownerAddress !== process.env.WALLET_ADDRESS &&
            //data.data[i].minted === false &&
            data.data[i]._id &&
             data.data[i].dataHash
           ) {
            console.log("inside 1st if ");
            if (noncecount === 0) {
               console.log("inside if");
               noncecount = await web3.eth.getTransactionCount(
              process.env.WALLET_ADDRESS,
                'pending'
               );
               console.log('inside if', noncecount);
             } else {
               console.log('inside else');
               noncecount++;
             }
             console.log("ID",data.data[i]._id);
             console.log("ID",typeof(data.data[i]._id));
              let data1 = poolContract.methods.mintNft(
               process.env.WALLET_ADDRESS,
               data.data[i]._id.toString(),
               data.data[i].commodityId.toString(),
               data.data[i].quantity,
               data.data[i].nftPrice,
               data.data[i].dataHash,
               JSON.stringify(nftObject)
             );
             console.log('nonce here', noncecount);
             const tx1 = {
              from: process.env.WALLET_ADDRESS,
              to: poolAddress,
              nonce: noncecount,
              gasLimit: '0xFFFFF1',
             // maxPriorityFeePerGas: '0x12A05F200',
              data: data1.encodeABI(),
            };
            console.log('----------tx----', tx1);
            var signPromise = await web3.eth.accounts.signTransaction(
              tx1,
              process.env.PRIVATE_KEY
            );
              console.log(signPromise);
            var receipt = await web3.eth.sendSignedTransaction(
              signPromise.raw || signPromise.rawTransaction
            );
            console.log(
              'final receipt here-------------------------',
              receipt.transactionHash
            );

            let nftresult = await poolContract.methods.nft(data.data[i]._id.toString()).call();
            console.log(nftresult,data.data[i].id,"nftResult")
              data.data[i].minted = true;
              data.data[i].ownerAddress =process.env.WALLET_ADDRESS;
             data.data[i].mintedTransactionHash = receipt.transactionHash;
    //       //  data.data[i].ownerAddress="place your owner address"

            //  const updatedNft = await NFT.findByIdAndUpdate(data.data[i]._id, data.data[i], {
            //   new: true,
            // });
    //         console.log(updatedNft);
             totalMintedAmount += data.data[i].nftPrice;
             console.log('----------', totalMintedAmount);
           } else if (data.data[i].nftPrice &&  data.data[i].nftPrice % 1 == 0) {
             totalMintedAmount += data.data[i].nftPrice;
             console.log('----------totalamount', totalMintedAmount);
             continue;
           }

       
      }

    
  } catch (error) {
    console.log(error);
  }
}
main()
const autoMint = async function () {
  console.log('Running CRON ****************');
  // cron.schedule(
  //     '*/10 * * * *',
  //     () => {
  main()
    .then(() => {
      // process.exit(0)
    })
    .catch((error) => {
      console.error(error);
      // process.exit(1);
    });

  //     },
  //     {
  //         timezone: 'Asia/Kolkata',
  //         scheduled: true,
  //     }
  // );
};

module.exports.autoMint = autoMint;
