/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IBruProxy,
  IBruProxyInterface,
} from "../../../contracts/interfaces/IBruProxy";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "implementationAddress",
        type: "address",
      },
    ],
    name: "upgradeTo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IBruProxy__factory {
  static readonly abi = _abi;
  static createInterface(): IBruProxyInterface {
    return new utils.Interface(_abi) as IBruProxyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBruProxy {
    return new Contract(address, _abi, signerOrProvider) as IBruProxy;
  }
}
